---
- name: Update and upgrade all packages on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
